/**
 * @fileoverview Final Output Component
 * 
 * Final step of the patient communication workflow. Displays the
 * approved patient communication document and provides:
 * - Print functionality for patient handout
 * - Comprehension testing questions (teach-back method)
 * - Option to start a new case
 * 
 * @module components/FinalOutput
 */

import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { CheckCircle, Printer, Users, RotateCcw, Heart, ChevronLeft } from "lucide-react";
import { useCasePersistence } from "@/hooks/useCasePersistence";

/**
 * Props for the FinalOutput component
 */
interface FinalOutputProps {
  /** ID of the current case */
  caseId: string;
  /** Final approved text content */
  finalText: string;
  /** Callback to start a new patient case */
  onRestart: () => void;
  /** Callback to return to approval step for edits */
  onBack: () => void;
}

/** Questions for patient comprehension testing (teach-back method) */
const COMPREHENSION_QUESTIONS = [
  "Can you tell me in your own words what heart failure means?",
  "What should you do if your breathing becomes much worse?",
  "How much fluid should you drink each day?",
  "When is your next appointment with the cardiologist?",
  "What are your three main medications and what do they do?"
];

/**
 * Final Output Component
 * 
 * Displays the completed patient communication document with
 * print and comprehension testing functionality.
 * 
 * @example
 * ```tsx
 * <FinalOutput
 *   caseId="123-abc"
 *   finalText={approvedDocument}
 *   onRestart={() => startNewCase()}
 *   onBack={() => goToApproval()}
 * />
 * ```
 */
const FinalOutput = ({
  caseId,
  finalText,
  onRestart,
  onBack
}: FinalOutputProps) => {
  const [showComprehensionTest, setShowComprehensionTest] = useState(false);
  const { updateCase } = useCasePersistence();

  // Mark case as completed when component mounts
  useEffect(() => {
    const markCompleted = async () => {
      await updateCase(caseId, { status: 'completed' });
    };
    markCompleted();
  }, [caseId, updateCase]);

  /**
   * Opens a new window with printable document and triggers print dialog
   */
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Patient Communication - Heart Failure</title>
        <style>
          body { 
            font-family: 'Georgia', serif; 
            line-height: 1.6; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 20px;
            font-size: 16px;
          }
          h1 { color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }
          .header { text-align: center; margin-bottom: 30px; }
          .content { white-space: pre-wrap; }
          .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 14px; color: #666; }
          @media print {
            body { font-size: 14px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Patient Communication</h1>
          <p>Heart Failure Information and Care Instructions</p>
        </div>
        <div class="content">${finalText.replace(/\n/g, '<br>')}</div>
        <div class="footer">
          <p>Generated by Doctor Bridge | Clinically Approved | ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  /**
   * Toggles visibility of comprehension test section
   */
  const toggleComprehensionTest = () => {
    setShowComprehensionTest(prev => !prev);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Main Document Card */}
      <Card className="shadow-card">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <CheckCircle className="h-5 w-5 text-success" />
              <CardTitle>Final Patient Communication</CardTitle>
            </div>
            <div className="flex items-center space-x-2">
              <Badge variant="default" className="bg-success text-success-foreground">
                Clinically Approved
              </Badge>
              <Badge variant="outline">
                Ready for Patient
              </Badge>
            </div>
          </div>
          <CardDescription>
            Approved patient-friendly communication ready for printing and delivery.
          </CardDescription>
        </CardHeader>
        
        <CardContent className="space-y-6">
          {/* Document Preview */}
          <div className="bg-card border border-border rounded-lg p-8 shadow-sm print:shadow-none">
            <div className="text-center mb-6">
              <div className="flex items-center justify-center space-x-2 mb-2">
                <Heart className="h-6 w-6 text-primary" />
                <h2 className="text-2xl font-bold text-foreground">Patient Communication</h2>
              </div>
              <p className="text-muted-foreground">Heart Failure Information and Care Instructions</p>
            </div>
            
            <Separator className="my-6" />
            
            <div className="whitespace-pre-wrap font-mono text-base leading-relaxed text-foreground">
              {finalText}
            </div>
            
            <Separator className="my-6" />
            
            <div className="text-center text-sm text-muted-foreground">
              <p>Generated by Doctor Bridge | Clinically Approved | {new Date().toLocaleDateString()}</p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-3 justify-center">
            <Button onClick={onBack} variant="outline" className="flex items-center space-x-2">
              <ChevronLeft className="h-4 w-4" />
              <span>Review & Edit Patient Communication</span>
            </Button>
            
            <Button onClick={handlePrint} className="flex items-center space-x-2">
              <Printer className="h-4 w-4" />
              <span>Print for Patient</span>
            </Button>
            
            <Button 
              variant="outline" 
              onClick={toggleComprehensionTest}
              className="flex items-center space-x-2"
            >
              <Users className="h-4 w-4" />
              <span>Comprehension Test</span>
            </Button>
            
            <Button 
              variant="outline" 
              onClick={onRestart}
              className="flex items-center space-x-2"
            >
              <RotateCcw className="h-4 w-4" />
              <span>New Patient</span>
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Comprehension Test Section */}
      {showComprehensionTest && (
        <Card className="bg-medical-light-blue border-primary/20">
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <Users className="h-5 w-5 text-primary" />
              <span>Patient Comprehension Assessment</span>
            </CardTitle>
            <CardDescription>
              Use these questions to verify patient understanding (teach-back method)
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <h3 className="font-semibold">Ask the patient these questions:</h3>
              <div className="space-y-3">
                {COMPREHENSION_QUESTIONS.map((question, index) => (
                  <div
                    key={index}
                    className="flex items-start space-x-3 p-3 bg-background rounded-lg border border-border"
                  >
                    <div className="w-6 h-6 bg-primary text-primary-foreground rounded-full flex items-center justify-center text-sm font-medium">
                      {index + 1}
                    </div>
                    <p className="text-sm">{question}</p>
                  </div>
                ))}
              </div>
              
              <div className="mt-6 p-4 bg-warning/10 border border-warning/20 rounded-lg">
                <h4 className="font-semibold text-warning mb-2">Assessment Notes:</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• Document patient responses in medical record</li>
                  <li>• If patient cannot answer correctly, provide additional explanation</li>
                  <li>• Consider involving family members if patient struggles with comprehension</li>
                  <li>• Schedule follow-up education session if needed</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Status Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="bg-success/5 border-success/20">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-2 mb-2">
              <CheckCircle className="h-4 w-4 text-success" />
              <h3 className="font-semibold text-success">Process Complete</h3>
            </div>
            <p className="text-sm text-muted-foreground">
              Patient communication approved and ready for delivery
            </p>
          </CardContent>
        </Card>

        <Card className="bg-primary/5 border-primary/20">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-2 mb-2">
              <Printer className="h-4 w-4 text-primary" />
              <h3 className="font-semibold text-primary">Print Ready</h3>
            </div>
            <p className="text-sm text-muted-foreground">
              Formatted for A4 printing with accessible typography
            </p>
          </CardContent>
        </Card>

        <Card className="bg-accent/5 border-accent/20">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-2 mb-2">
              <Users className="h-4 w-4 text-accent" />
              <h3 className="font-semibold text-accent">Family Included</h3>
            </div>
            <p className="text-sm text-muted-foreground">
              Content adapted for patient and caregiver understanding
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default FinalOutput;
